<a href="https://colab.research.google.com/github/BlancJH/Forecasting-Machine-Learning/blob/main/Weather_Forecasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

In [2]:
# Import modules
import pandas as pd

In [5]:
# Load datasets
file_path_asos = r'/ASOS_DATA.csv'
asos = pd.read_csv(file_path_asos)

file_path_geo = r'/GEO_DATA.csv'
geo = pd.read_csv(file_path_geo, encoding='euc-kr')

In [6]:
# Replacing Korean Region names to English alphabet
geo['STN_KO'] = geo['STN_KO'].str.replace('철원', 'Cheol_Won')
geo['STN_KO'] = geo['STN_KO'].str.replace('춘천', 'Choon_Cheon')
geo['STN_KO'] = geo['STN_KO'].str.replace('북강릉', 'Buk_Gang_Reung')
geo['STN_KO'] = geo['STN_KO'].str.replace('강릉', 'Gang_Reung')
geo['STN_KO'] = geo['STN_KO'].str.replace('서울', 'Seoul')
geo['STN_KO'] = geo['STN_KO'].str.replace('인천', 'Incheon')
geo['STN_KO'] = geo['STN_KO'].str.replace('울릉도', 'Ul_Reung_Do')
geo['STN_KO'] = geo['STN_KO'].str.replace('수원', 'Suwon')
geo['STN_KO'] = geo['STN_KO'].str.replace('서산', 'Seo_San')
geo['STN_KO'] = geo['STN_KO'].str.replace('청주', 'Cheong_Ju')
geo['STN_KO'] = geo['STN_KO'].str.replace('대전', 'Dae_Jeon')
geo['STN_KO'] = geo['STN_KO'].str.replace('안동', 'Ahn_Dong')
geo['STN_KO'] = geo['STN_KO'].str.replace('전주', 'Jeon_Ju')
geo['STN_KO'] = geo['STN_KO'].str.replace('부산', 'Busan')
geo['STN_KO'] = geo['STN_KO'].str.replace('목포', 'Mok_Po')
geo['STN_KO'] = geo['STN_KO'].str.replace('여수', 'Yeo_Su')
geo['STN_KO'] = geo['STN_KO'].str.replace('제주', 'Jeju')

In [7]:
geo

,STN_ID,TM_ED,TM_ST,STN_KO,STN_SP,LAT,LON,HT,HT_WD,LAU_ID,STN_AD,FCT_ID,BASIN_ID,BASIN_REP_ID,Region,City
0,95,2015.07.13.00:00,1998.12.22.17:00,Cheol_Won,41111211,38.14788,127.30420,153.70,12.6,4095,95,11D10101,강원도 철원군 갈말읍 군탄리,강원도 철원군 갈말읍 군탄리,강원도,철원군
1,101,2100.12.31.00:00,2013.08.01.14:28,Choon_Cheon,41211111,37.90256,127.73570,77.71,10.0,4101,101,11D10301,강원도 춘천시 우두동,강원도 춘천시 우두동,강원도,춘천시
2,104,2100.12.31.00:00,2008.07.01.00:00,Buk_Gang_Reung,41111111,37.80456,128.85535,78.90,10.0,4105,105,11D20501,강원도 강릉시 사천면 방동리,강원도 강릉시 사천면 방동리,강원도,강릉시
3,105,2100.12.31.00:00,2005.01.01.00:00,Gang_Reung,41111111,37.75147,128.89098,26.04,17.9,4105,105,11D20501,강원도 강릉시 용강동,강원도 강릉시 용강동,강원도,강릉시
4,108,2100.12.31.00:00,2010.08.16.00:00,Seoul,41111111,37.57141,126.96579,85.80,10.0,4108,109,11B10101,서울특별시 종로구 송월동,서울특별시 종로구 송월동,서울특별시,종로구
5,112,2100.12.31.00:00,2012.06.01.11:10,Incheon,41211111,37.47770,126.62490,71.43,10.0,4112,112,11B20201,인천광역시 중구 전동,인천광역시 중구 전동,인천광역시,중구
6,115,2015.07.13.00:00,1999.03.29.16:00,Ul_Reung_Do,41111211,37.48129,130.89864,222.80,10.0,4115,115,1.10E+102,경상북도 울릉군 울릉읍 도동리,경상북도 울릉군 울릉읍 도동리,경상북도,울릉군
7,119,2013.08.01.13:10,1998.12.28.18:00,Suwon,41111000,37.27230,126.98530,34.06,18.7,4119,119,11B20601,경기도 수원시 권선구 서둔동,경기도 수원시 권선구 서둔동,경기도,수원시
8,129,2100.12.31.00:00,2012.06.01.11:20,Seo_San,41211111,36.77661,126.49391,28.91,20.2,4129,177,11C20101,충청남도 서산시 수석동,충청남도 서산시 수석동,충청남도,서산시
9,131,2100.12.31.00:00,1998.12.24.14:00,Cheong_Ju,41111111,36.63924,127.44066,57.16,10.0,4131,131,11C10301,충청북도 청주시흥덕구 복대동,충청북도 청주시흥덕구 복대동,충청북도,청주시흥덕구
10,133,2100.12.31.00:00,2012.06.01.10:30,Dae_Jeon,41211111,36.37200,127.37212,68.94,19.8,4133,133,11C20401,대전광역시 유성구 구성동,대전광역시 유성구 구성동,대전광역시,유성구
11,136,2100.12.31.00:00,1998.12.24.17:00,Ahn_Dong,41111111,36.57293,128.70732,140.10,10.0,4136,136,11H10501,경상북도 안동시 운안동,경상북도 안동시 운안동,경상북도,안동시
12,146,2015.05.23.18:00,1998.12.22.21:00,Jeon_Ju,41111111,35.82150,127.15496,53.40,18.4,4146,146,11F10201,전라북도 전주시완산구 남노송동,전라북도 전주시완산구 남노송동,전라북도,전주시완산구
13,146,2015.07.01.00:00,2015.05.23.18:00,Jeon_Ju,41211111,35.82150,127.15496,53.40,18.4,4146,146,11F10201,전라북도 전주시완산구 남노송동,전라북도 전주시완산구 남노송동,전라북도,전주시완산구
14,146,2100.12.31.00:00,2015.07.01.00:00,Jeon_Ju,41111111,35.84080,127.11720,61.40,10.0,4146,146,11F10201,전라북도 전주시덕진구 덕진동2가,전라북도 전주시덕진구 덕진동2가,전라북도,전주시덕진구
15,159,2100.12.31.00:00,1999.03.29.16:00,Busan,41111111,35.10468,129.03203,69.56,17.8,4159,159,11H20201,부산광역시 중구 대청동1가,부산광역시 중구 대청동1가,부산광역시,중구
16,165,2100.12.31.00:00,2012.06.01.13:10,Mok_Po,41211111,34.81689,126.38121,38.00,15.5,4165,165,21F20801,전라남도 목포시 연산동,전라남도 목포시 연산동,전라남도,목포시
17,168,2100.12.31.00:00,2012.06.01.09:30,Yeo_Su,41211211,34.73929,127.74064,64.64,20.8,4168,168,11F20401,전라남도 여수시 고소동,전라남도 여수시 고소동,전라남도,여수시
18,184,2100.12.31.00:00,2012.06.01.13:30,Jeju,41211111,33.51411,126.52968,20.45,12.3,4184,184,11G00201,제주특별자치도 제주시 건입동,제주특별자치도 제주시 건입동,제주특별자치도,제주시